
GET http://localhost:5500/api/books

###

GET http://localhost:5500/api/books/67f76eab460ee13923f79921

###

POST http://localhost:5500/api/books
content-type: application/json

{
  "title": "Harry Potter and the Philosopher's Stone",
  "author": "J.K. Rowling",
  "publishedYear": 1997,
  "genre": "Fantasy"
}

### 

PUT http://localhost:5500/api/books/67f76eab460ee13923f79921
content-type: application/json

{
  "title": "1984",
  "author": "George Orwell",
  "genre": ["Dystopian", "Political Fiction"],
  "publishedYear": 1949
}

###

DELETE http://localhost:5500/api/books/67f76eab460ee13923f79921
